jenkinsci/winstone

pom.xml, src/java/winstone/Ajp13ConnectorFactory.java, src/java/winstone/HttpConnectorFactory.java, src/java/winstone/HttpsConnectorFactory.java, src/java/winstone/Launcher.java, src/java/winstone/cmdline/Option.java, src/test/winstone/Ajp13ConnectorFactoryTest.java
As a part of upgrading Jenkins to servlet 3.1, we need Winstone to support servlet 3.1, which this PR does by pulling in Jetty 9.2, which is the latest version of Jetty that runs on Java7.
Notable incompatibilities include:
* Lack of AJP support ([link](https://github.com/eclipse/jetty.project/issues/134))
* requestBufferSize setting in Jetty8 appears to have no counterpart
This PR is to let others comment on the changes thus far, find those missing features from somewhere, and try it out on Jenkins. Once we decide to drop those functionalities, we need a follow-up change to clean up the help screen, really remove AJP related code, etc.
=> [JENKINS-23378] Jetty9 upgrade

src/java/winstone/HostConfiguration.java
It seems that context must not be started upon creation in HostConfiguration (which is already the case for single webapp). Removing those two lines seems to fix multi webapp support, which otherwise is broken with this error message:
```
Sep 10, 2015 7:41:04 PM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: FAILED org.eclipse.jetty.server.session.HashSessionManager@39dd3812: java.lang.NullPointerException
java.lang.NullPointerException
at org.eclipse.jetty.server.session.AbstractSessionManager.doStart(AbstractSessionManager.java:239)
at org.eclipse.jetty.server.session.HashSessionManager.doStart(HashSessionManager.java:92)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
at org.eclipse.jetty.server.session.SessionHandler.doStart(SessionHandler.j …
```
=> Multi Webapp support fixed

Jenkinsfile
Updates the Jenkinsfile to use JDK8 for the builds.
@reviewbybees   Blocked by #23
=> update ci build to use JDK8

src/java/winstone/HostConfiguration.java, src/java/winstone/Launcher.java
As it stands right now, empty Jetty keeps running and makes it difficult
to detect catastrophic boot error.
The code change makes any exception thrown from ServletContextListener a
fatal problem.
https://issues.jenkins-ci.org/browse/JENKINS-42159
=> [FIXED JENKINS-42159] If startup fails, exit the process.

README.md
The previous documentation is just incorrect for the new release: we use Jetty 9.4 && do not support SPDY anymore.
@reviewbybees @olamy
=> README: Update documentation to reflect the Winstone 4 state

README.md
Rather than
> the gut of Winstone has been removed and delegated Jetty
instead
> the gut of Winstone has been removed and delegated to Jetty
=> trivial README edit: delegated *to* Jetty

CHANGELOG.md, README.md, src/java/winstone/cmdline/Option.java
@olamy @dwnusbaum I have released 4.1.1 for testing on the Master's side. Actually it should have been a staged timestamped snapshot, but it was too late when I realised that. In the worst case we can mark release as burned one
For now I did some polishing: https://issues.jenkins-ci.org/browse/JENKINS-49596
@reviewbybees
=> [JENKINS-49596] - Increase timeout to 30 min, Noting 4.1.1 and adding it to documentation

CHANGELOG.md, README.md, pom.xml, src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> add an option to enable jetty jmx

pom.xml
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.12.v20180830
It contains some fixes towards Java 9+, it makes sense to pick-up the update
@olamy @jenkinsci/sig-platform
=> Update Jetty to 9.4.12.v20180830

CHANGELOG.md, README.md, pom.xml, src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
since jetty 9.4.12.v20180830 default cipher exclusion has been changed with https://github.com/eclipse/jetty.project/issues/2807. We need  a configuration parameter so the user can choose their prefer exclusion list.
=> JENKINS-56591 cipher exclusion configurable

src/main/java/winstone/tools/WinstoneControl.java
try-with-resources was introduced in [this commit](https://github.com/jenkinsci/winstone/commit/aed91a80cd509da955f749c4539bc3599ef87ee6#commitcomment-33011448) and therefore the stream must not be closed manually.
@olamy
=> Stream does not need to be closed given try-with-resources is in place.

pom.xml, src/main/java/winstone/Launcher.java
API from https://github.com/jenkinsci/support-core-plugin/pull/168, now to produce one-line logs from `jenkins.war`. [Discussion](https://groups.google.com/d/msg/jenkinsci-dev/4PTMMwQNfjw/qVZBT379BgAJ)
```
…
2019-04-10 23:23:36.149+0000 [id=46]	INFO	hudson.model.UpdateSite#updateData: Obtained the latest update center data file for UpdateSource default
2019-04-10 23:23:36.507+0000 [id=32]	INFO	hudson.model.UpdateSite#updateData: Obtained the latest update center data file for UpdateSource default
2019-04-10 23:23:36.773+0000 [id=46]	INFO	h.m.DownloadService$Downloadable#load: Obtained the updated data file for hudson.tasks.Maven.MavenInstaller
…
```
@jenkinsci/code-reviewers esp. @batmat
=> Using SupportLogFormatter

CHANGELOG.md, pom.xml
- Changelog [here](https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.19.v20190610)
=> Update jetty to 9.4.19

.dependabot/config.yml, .github/release-drafter.yml
To avoid the need for manual stuff like #68. On hold pending [INFRA-2317](https://issues.jenkins-ci.org/browse/INFRA-2317) so I can enable these apps.
=> Configuration for Release Drafter and Dependabot

src/main/resources/winstone/LocalStrings.properties
This version number has been wrong for more than two years (since https://github.com/jenkinsci/winstone/releases/tag/winstone-4.1)
Better to just give up.
It's apparently only used in two messages (a log message and usage instructions) anyway.
Semi-related to [JENKINS-33814](https://issues.jenkins-ci.org/browse/JENKINS-33814), which was about the same problem in early 2016.
=> Remove version number

pom.xml, src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/Ajp13ConnectorFactory.java, src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/HostGroup.java, src/main/java/winstone/Launcher.java, src/main/java/winstone/Logger.java, src/main/java/winstone/WinstoneSession.java, src/main/java/winstone/accesslog/SimpleAccessLogger.java, src/main/java/winstone/cmdline/CmdLineParser.java, src/main/java/winstone/realm/FileRealm.java, src/main/java/winstone/tools/WinstoneControl.java, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/testApplication/filters/TimingFilter.java, src/test/java/winstone/testCase/HttpConnectorTest.java, src/test/java/winstone/testCase/load/LoadTest.java
- Swapped to spotbugs and fixed multiple issues.
- There still remains some issues but the PR was getting large
=> Switch to spotbugs and fix some issues

pom.xml
See https://github.com/jenkinsci/jep/pull/250.
=> [JEP-222] - Add WebSocket support

src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/Launcher.java, src/main/java/winstone/WinstoneSession.java
Corrects a regression from #69 found by @jeffret-b: https://github.com/jenkinsci/jenkins/pull/4369#issuecomment-570639297
See: https://github.com/jenkinsci/extras-executable-war/blob/2af94677c0ba557351d2c0703c3c43030c198b50/src/main/java/Main.java#L343-L371
=> Various regressions from earlier code cleanup

src/main/java/winstone/Launcher.java
[JENKINS-60821](https://issues.jenkins-ci.org/browse/JENKINS-60821) 
by default any thread created from a QueudThreadPool has `qtp` as the
base of its name.  Given there could be other usage of QueuedThreadPool
and that it is usefull to be friendly set the name of the threadpool so
something helpful and hopefully unique.
=> [JENKINS-60821] set the name of Jetty's thread pool

src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/Launcher.java, src/test/java/winstone/FormSubmissionTest.java, src/test/java/winstone/testApplication/servlets/AcceptFormServlet.java, src/testwebapp/WEB-INF/web.xml
[JENKINS-60409](https://issues.jenkins-ci.org/browse/JENKINS-60409)
Amending #20 because this feature stopped working after #68 in 5.4 with https://github.com/eclipse/jetty.project/pull/3899.
* run a Jenkins `master` build
* install `kubernetes` plugin
* add a K8s cloud
* start adding pod templates and clicking **Apply** until the error is seen (once the `Content-Length` goes above 200_000)
* apply
```diff
diff --git war/pom.xml war/pom.xml
index 3f816fb897..c5d0355ab1 100644
--- war/pom.xml
+++ war/pom.xml
@@ -100,7 +100,7 @@ THE SOFTWARE.
-->
<groupId>org.jenkins-ci</groupId>
<artifactId>winstone</artifactId>
-      <version>5.8</version>
+      <version>5.9-rc529.8a8a146c88e5</version>
<scope>test</scope>
</dependency>
<dependency>
```
* run with this patched WAR
* add some more pod …
=> [JENKINS-60409] --requestFormContentSize no longer works

.mvn/extensions.xml, .mvn/maven.config, Jenkinsfile, pom.xml, src/main/java/winstone/Launcher.java
Alternative solution for the 2.204.3 and 2.204.4 issues caused by the unintended Jetty upgrade. Instead of playing whack-a-mole with Jetty, I suggest reverting the updates and going forward with a new Winstone version which is based on Winstone 5.4 and includes bugfixes unrelated to Jetty.
Changes to be backported:
* [JENKINS-60821](https://issues.jenkins-ci.org/browse/JENKINS-60821) - set the _Jetty (winstone)_ name for the Jetty's thread pool (#90) @jtnord
* [JENKINS-57888](https://issues.jenkins-ci.org/browse/JENKINS-57888) - Restore `java.util.logging.config.file` property support (regression in 5.4) (#87) @lrpg
* Enable releases of Incremental versions ([JEP-305](https://github.com/jenkinsci/jep/tree/master/jep/305)) (#81) @jglick
* …
=> [JENKINS-60409, JENKINS-60199] - Winstone 5.4.1 backports for Jenkins 2.204.x

pom.xml
Picks up https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.33.v20201019 which includes a fix for https://github.com/eclipse/jetty.project/issues/5417 fix is out (PR: https://github.com/eclipse/jetty.project/pull/5419 ). 
This is a foundation for a better fix than https://github.com/jenkinsci/jenkins/pull/5017
CC @jenkinsci/core
=> [JENKINS-63958] - Update Jetty from 9.4.32.v20200930 to 9.4.33.v20201020

src/main/java/winstone/AbstractSecuredConnectorFactory.java
[JENKINS-66379](https://issues.jenkins.io/browse/JENKINS-66379)
The JKS keystore is insecure and is some environments not even allowed.
We do not care what format the keystore is in, so just use the default.
If someone has a non default keystore yet is using a keystore here then
this will break on upgrade, however it is unlikely that they would be
having a non default keystore as the normal reason for doing that is due
to a restriction like FIPS-140 and given the keystore we require has a
key using JDK here would be non compliant.
no unit tests as this requires changing java security properties for the JVM.  Existing tests will ensure there are no regressions for the normal cases.
=> [JENKINS-66379] use default keystore format

src/main/java/winstone/AbstractSecuredConnectorFactory.java
Per [the Javadoc](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/B64Code.html):
> Unlike `decode(char[])`, extra whitespace is ignored.
Therefore I added a `trim()` to the string to strip extra whitespace before passing the result to `Base64.getDecoder().decode()`.
CC @olamy
=> Replace deprecated `org.eclipse.jetty.util.B64Code` with non-deprecated `java.util.Base64`

pom.xml
Fixes the following build warning:
```
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
```
=> Use UTF-8 source encoding

src/main/java/winstone/Http2ConnectorFactory.java
see [JENKINS-66745](https://issues.jenkins.io/browse/JENKINS-66745)
Simple fix -- tweak the default protocol, presumed when ALPN header is not sent, to be http/1.1 -- this allows pre-ALPN clients like curl/wget on RH7 boxes, to properly access the http/2 port in Winstone.
=> [JENKINS-66745] Winstone: http/2 port not backward compatible with ALPN http/1.1 clients

src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Before adding this sleep, this test would flake about half the time as in [this run](https://ci.jenkins.io/job/Core/job/winstone/job/master/252/testReport/winstone.accesslog/SimpleAccessLoggerTest/testSimpleConnection/). After adding this sleep I have run the test 10 times in a row without any flakes.
=> Make test less flaky

src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Reworked Test case to check every 100ms and break out the loop once a response has been written to the log file.
Fixes https://github.com/jenkinsci/winstone/issues/231
=> Rework 5s sleep with 100ms intervals

README.md, src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/HttpsConnectorFactoryTest.java
Fixes https://github.com/jenkinsci/winstone/issues/213
Test needs re-implementing to use a keystore (that mode wasn't tested before afaict)
Support has been removed for PEM encoded certificates when running Jenkins with the embedded Jetty (winstone) container and TLS.
Specifically the flags `--httpsPrivateKey` and `--httpsCertificate` have been removed.
Users who were previously using this feature must use a KeyStore instead.  See the [documentation](https://www.jenkins.io/doc/book/installing/initial-settings/#https-with-an-existing-certificate) for details.
This feature has been logging deprecation warnings on startup since 2016.
=> Remove ability to load pem cert for winstone

src/main/java/winstone/HostConfiguration.java
Improve the comment from #246 to more accurately reflect what the code is doing, and improve the error message to state the name of the problematic entry when the condition is encountered.
CC @JLLeitschuh @daniel-beck
=> Improve comment and error message

pom.xml
The version here is redundant, as it is specified in [the parent POM](https://github.com/jenkinsci/pom/blob/8992541180d91c628488f94db69b5ebcc7e97062/pom.xml#L140). Additionally, duplicating it here results in undesirable Dependabot spam. By removing the explicit and redundant version number, we reduce both unnecessary duplication and Dependabot spam.
=> Remove redundant version

pom.xml
Newer versions of Rhino are not compatible with [HttpUnit](http://httpunit.sourceforge.net/).
=> Upgrade Rhino from 1.7R2 to 1.7R5

pom.xml
This has been unneeded since we dropped support for Java 8.
=> Remove unneeded managed dependency entry

pom.xml, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/FormSubmissionTest.java, src/test/java/winstone/HttpsConnectorFactoryTest.java, src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
Drops usages of the Apache Commons I/O library in tests in favor of native Java Platform functionality. It is generally desirable to have fewer dependencies, because that reduces the risk of problems when upgrading dependencies or using outdated versions.
=> Drop `commons-io` dependency in favor of native Java Platform functionality

pom.xml
The version here is redundant, as it is specified in [the parent POM](https://github.com/jenkinsci/pom/blob/8992541180d91c628488f94db69b5ebcc7e97062/pom.xml#L125). Additionally, duplicating it here results in undesirable Dependabot spam. By removing the explicit and redundant version number, we reduce both unnecessary duplication and Dependabot spam.
=> Remove redundant `maven-antrun-plugin` version

pom.xml
Jetty depends on `org.slf4j:slf4j-api` without providing an implementation, which forces us to provide one by depending on `org.slf4j:slf4j-jdk14`. Since pending [SLF4J-437](https://jira.qos.ch/browse/SLF4J-437) SLF4J provides no BOM, this creates challenges for Dependabot updates as seen in https://github.com/jenkinsci/winstone/pull/235#pullrequestreview-1017970886: Dependabot's update to the version of `slf4j-jdk14` creates an Enforcer error with the version of `slf4j-api` that Jetty depends on.
Pending SLF4J-437, manage both `slf4j-api` and `slf4j-jdk14` in a `<dependencyManagement>` section whose version is controlled by a single Maven property. When Dependabot updates this property, the managed dependencies for both the API and implementation get updated, and the Enforcer error will …
=> Manage both SLF4J API and SLF4J implementation versions

src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/realm/ArgumentsRealmTest.java
Like https://github.com/jenkinsci/jenkins/pull/7114. Some test cleanup, mainly eliminating usages of try/fail/catch in favor of the more legible alternative offered by JUnit 4.13 in the form of `Assert#assertThrows`.
=> Prefer `assertThrows` to try/fail/catch

pom.xml, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/FormSubmissionTest.java, src/test/java/winstone/HttpConnectorFactoryTest.java, src/test/java/winstone/LauncherTest.java, src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java, src/test/java/winstone/realm/ArgumentsRealmTest.java, src/test/java/winstone/testCase/HttpConnectorTest.java, src/test/java/winstone/testCase/load/LoadTest.java, src/test/java/winstone/testCase/load/LoadTestThread.java
The test suite has a dependency on [HttpUnit](http://httpunit.sourceforge.net/), last released in 2008 and which in turn depends on an obsolete version of Rhino. This does not seem sustainable.
Migrate to the native HTTP client offered in Java 9+.
Note that `testKeepAliveConnection` appears to have never been completed; in practice, the `WebImage[] img = wresp1.getImages()` line was always returning an empty array, making this test equivalent to `testSimpleConnection`. The commented out lines also appear to indicate that the attempt to finish this test was abandoned. Since this test never worked to begin with and duplicated an existing test, I simply deleted it.
`LoadTest` appears to have been completely broken before this PR, but as of this PR it now works:
```
Sep 18, 2022 2:51:08 PM …
```
=> Migrate from HttpUnit to native Java Platform functionality

pom.xml
This doesn't convert tests to JUnit 5, but it does add support for JUnit 5 in the test suite, and it runs the existing JUnit 4 based tests using the JUnit 5 Vintage engine, consistent with the way we now run tests in Jenkins core and plugins.
=> Run tests with JUnit Jupiter

pom.xml
I noticed `Including com.github.spotbugs:spotbugs-annotations:jar:4.7.2 in the shaded jar` when doing a build recently. We don't need the SpotBugs annotations at runtime, so this just bloats the build. With this change, the same line in the build now reads `[INFO] Excluding com.github.spotbugs:spotbugs-annotations:jar:4.7.2 from the shaded jar`.
=> Exclude SpotBugs annotations from shaded JAR

pom.xml
Creating an `enable-jacoco` Maven profile enables our existing `Jenkinsfile` to provide code coverage information for CI runs.
=> Enable JaCoCo in CI runs

pom.xml, src/main/java/winstone/Http2ConnectorFactory.java, src/test/java/winstone/Http2ConnectorFactoryTest.java
Running Winstone in HTTP/2 mode fails with
```
WARNING: Failed to start ALPN
java.lang.IllegalStateException: No Server ALPNProcessors!
at org.eclipse.jetty.alpn.server.ALPNServerConnectionFactory.<init>(ALPNServerConnectionFactory.java:47)
at winstone.Http2ConnectorFactory.start(Http2ConnectorFactory.java:79)
at winstone.Launcher.spawnListener(Launcher.java:269)
at winstone.Launcher.<init>(Launcher.java:185)
```
I reproduced this error in an integration test.
As of https://github.com/eclipse/jetty.project/issues/215 and https://github.com/eclipse/jetty.project/issues/2948 (specifically, eclipse/jetty.project@0303ae4aafe20c6177a834320da90cb89944c01b, eclipse/jetty.project@8b14cbe5f873d7b930ded9872675520d2cf2cf90, eclipse/jetty.project@1fe6c92ee9cce80c180eafb792435b7b6af3d86c, and …
=> [JENKINS-69638] HTTP/2 broken after Jetty 10 upgrade

pom.xml, src/test/java/winstone/HttpsConnectorFactoryTest.java
`HttpsConnectorFactoryTest` was using `HttpsURLConnection` to do its testing, which is inconsistent with all other tests that use the Java 11 HTTP client. This PR adapts that test to be consistent with all the other tests by using the Java 11 HTTP client.
While `HttpsURLConnection` could be instructed to disable hostname verification programmatically on a per-connection basis, it was a deliberate decision to not add a hostname verifier API to the Java 11 HTTP Client. Strict hostname verification is enabled by default and can only be disabled by setting a global system property. Doing so forces us to disable re-use of forks in Surefire, since tests now manipulate static JVM state that should not be shared with other tests. While we were updating the Surefire configuration, we also set an …
=> Use Java 11 HTTP client in `HttpsConnectorFactoryTest`

README.md
Amends #282. As of that PR, we now ship `jetty-alpn-java-server` out-of-the-box by default, so HTTP/2 "just works" without the need for complicated custom configuration.
=> Remove outdated HTTP/2 documentation

README.md, src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
Winstone requires Java 11 or newer, where `tools.jar` no longer exists. This implies that the `--toolsJar` is now unusable, but that option still exists.
Remove the `tools.jar` option, which no longer has any meaning under Java 11. While here, I also removed the `--useJasper`, which did nothing other than log a warning when `--toolsJar` was not provided and `--useJasper` was true. So removing `--toolsJar` means that the only use of `--useJasper` would be to log a warning if it is provided. So I removed it as well.
For some deeper context, see [the original Winstone docs](http://winstone.sourceforge.net/): `--useJasper` and `--toolsJar` were designed to support a Java 1.4-era use case of running JSP with Jasper. We do not test such a mode or have a use for JSP, and there is no doubt some …
=> Remove unused JSP options

README.md, src/main/java/winstone/WinstoneSession.java, src/main/resources/winstone/LocalStrings.properties
This was inlined to Jenkins core in https://github.com/jenkinsci/jenkins/pull/6706.
=> Remove dead references to `executable-war`

src/main/java/winstone/Launcher.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/LauncherTest.java
The `--extraLibFolder` option was originally added in #53 for HTTP/2 support. While potential secondary use cases remain, the primary use case no longer exists as of #282. Deprecating this functionality so that it can hopefully be removed in the future to ease the burden of maintaining this component.
=> Deprecate `--extraLibFolder` option

src/main/resources/winstone/LocalStrings.properties
Verified these were no longer used by running:
```
+ git grep -i ClusterNotFound
+ git grep -i ClusterOffNoControlPort
+ git grep -i ClusterStartupError
+ git grep -i HostsDirIsEmpty
+ git grep -i HostsDirIsNotDirectory
+ git grep -i HostsDirNotFound
+ git grep -i InitMultiComplete
+ git grep -i JNDIDisabled
+ git grep -i JNDIError
+ git grep -i ListenerNotFound
+ git grep -i ListenerStartupError
+ git grep -i NeedsJDK14
+ git grep -i NoPropertyFile
+ git grep -i NoWebRoot
+ git grep -i ParsingWebXml
+ git grep -i RequestHandlerThread
+ git grep -i StreamWriteError
+ git grep -i WebXmlParseComplete
+ git grep -i WebXmlParseFailed
```
=> Remove unused strings

src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
These options have been deprecated since 2018 in #54 and have long been no-ops.
=> Remove long-deprecated handler count options

src/main/java/winstone/Launcher.java
Fixes #219.
1. Run `java -jar war/target/jenkins.war`.
2. Press Control-C.
**Note:** These are the _actual_ results with this PR.
The application shutdown process prints the following logs:
```
2022-04-12 16:55:59.703+0000 [id=26]    INFO    winstone.Logger#logInternal: JVM is terminating. Shutting down Jetty
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.AbstractConnector#doStop: Stopped ServerConnector@6cd24612{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2022-04-12 16:55:59.710+0000 [id=26]    INFO    o.e.j.server.session.HouseKeeper#stopScavenging: node0 Stopped scavenging
2022-04-12 16:55:59.711+0000 [id=26]    INFO    hudson.lifecycle.Lifecycle#onStatusUpdate: Stopping Jenkins
2022-04-12 16:55:59.714+0000 [id=26]    INFO    jenkins.model.Jenkins$16#onAttained: Started …
```
=> Delay shutdown of logging facilities until the application has completed its shutdown process

pom.xml
Fixes the following Maven Shade Plugin warnings
```
[INFO] No artifact matching filter org.eclipse.jetty.orbit:javax.servlet
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] slf4j-api-2.0.6.jar, slf4j-jdk14-2.0.6.jar define 1 overlapping classes: 
[WARNING]   - META-INF.versions.9.module-info
[WARNING] http2-common-10.0.13.jar, http2-hpack-10.0.13.jar, http2-server-10.0.13.jar, jetty-alpn-java-server-10.0.13.jar, jetty-alpn-server-10.0.13.jar, jetty-http-10.0.13.jar, jetty-io-10.0.13.jar, jetty-jmx-10.0.13.jar, jetty-security-10.0.13.jar, jetty-server-10.0.13.jar, jetty-servlet-10.0.13.jar, jetty-servlet-api-4.0.6.jar, jetty-util-10.0.13.jar, jetty-webapp-10.0.13.jar, jetty-xml-10.0.13.jar, slf4j-api-2.0.6.jar, slf4j-jdk14-2.0.6.jar, …
```
=> Fix some Maven Shade Plugin warnings

README.md, src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
This PR adds a command-line option for users to specify excluded protocols.
Jetty already has a [default exclusion list](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L121)
Those values are added to the README
Closes #308
=> feat: add excludeProtocols command-line option

src/main/java/winstone/AbstractSecuredConnectorFactory.java
Fix a bug introduced in #312: we weren't trimming the comma-separated list after splitting it by commas, so the whitespace was resulting in the protocols not being added to the list. I tested this by setting a breakpoint in `org.eclipse.jetty.util.ssl.SslContextFactory#selectProtocols` and verifying that the list was the same as before #312.
=> Properly trim excluded protocols

src/main/java/winstone/Launcher.java
Amends #310. I observed a Jenkins log including
```
2023-01-27 19:48:23.847+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started Server@…{STARTING}[…,sto=0] @11198ms
java.lang.IllegalStateException: Shutdown in progress
at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:216)
at winstone.Launcher.<init>(Launcher.java:223)
at winstone.Launcher.main(Launcher.java:492)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at …
```
=> Tolerate `IllegalStateException` from `Runtime.addShutdownHook`

src/main/resources/winstone/mime.properties
Consistent with the default configuration of upstream Jetty and Nginx. (Apache httpd does not define a default MIME type for `.wasm` extensions, but presumably this is just a missing feature and they would accept a similar patch if offered one.)
=> Add WebAssembly MIME type

src/main/resources/winstone/mime.properties
This is a newer image format developed in 2019 by Netflix. The MIME type used here matches upstream Jetty and Nginx (Apache httpd does not have one, but this is presumably a missing feature for which they would accept a patch like this one.)
=> Add AV1 Image File Format (AVIF) MIME type

README.md, pom.xml, src/main/java/winstone/HttpConnectorFactory.java, src/main/java/winstone/HttpsConnectorFactory.java, src/main/java/winstone/ServerConnectorBuilder.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/HttpConnectorFactoryTest.java
Added --httpUnixDomainPath option to specify a unix domain socket to bind to instead of a port.
Use jetty-client for HTTP client tests, so that it is possible to test unix domain socket support. While JEP 380 added unix domain socket support to the JDK, java.net.http.HttpClient was overlooked.
Fixes https://github.com/jenkinsci/winstone/issues/345
Unit tests updated to support connection via both TCP ports and unix domain sockets.
```[tasklist]
```
=> Add support for Unix Domain Sockets.

src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
allow to make the client verification via a certificate optional.
fix #353
```[tasklist]
```
=> optional client certificate

pom.xml
- Remove unnecessary `<dependencyManagement>` entry (duplicated in parent POM)
- Remove unused repository
Tested with `mvn clean verify`.
=> Clean up POM

README.md, src/main/resources/winstone/LocalStrings.properties
commit a60ab16e84e0aec3ac9282240246953ce9fea2a4 from over a decade ago removed support for `--hostsDir`, but it missed a few lingering references in the `README` and in a localization file.
`git grep -i hostsdir` and `git grep -i hosts.dir`
=> Remove missed references to `--hostsDir`

README.md, src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/HostGroup.java, src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
Winstone contains 100 or so lines of code for a `--webappsDir` switch to run a directory full of WAR files, each with their own request logger which logs requests to a different file. There are no references to this in the `jenkinsci`, `jenkins-infra`, and `cloudbees` GitHub organizations. There is no test coverage for the feature. The single reference in Jira is [JENKINS-5307](https://issues.jenkins.io/browse/JENKINS-5307), from 2010. While I am aware of people running Jenkins as a WAR file in Tomcat alongside other WAR files, I am not aware of anyone using Winstone to run multiple WAR files. I think it is quite likely there are zero people using this feature.
This all is changing in Jetty 12, which now does request logging at a per-`Server` level, not a per-webapp level. Thus the …
=> Remove support for multiple WAR files

src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/Launcher.java, src/main/java/winstone/Logger.java, src/main/java/winstone/cmdline/CmdLineParser.java, src/main/java/winstone/cmdline/Option.java, src/main/java/winstone/realm/FileRealm.java, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/TrustManagerImpl.java, src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java, src/test/java/winstone/testApplication/filters/TimingFilter.java, src/test/java/winstone/testApplication/servlets/UnavailableServlet.java, src/test/java/winstone/testCase/load/LoadTest.java, src/test/java/winstone/testCase/load/LoadTestThread.java
More consistent with the general convention used throughout the Jenkins project.
https://www.imperialviolet.org/2014/02/22/applebug.html
`mvn clean verify -DskipTests`
=> Add missing braces to `if` statements

src/main/java/winstone/HostConfiguration.java
This is a trivial change, and I'm not really sure what its purpose is, but it was in Olivier's experiment, and it can be safely pushed to trunk, so why not push it to trunk to shrink the size of the other diff.
`mvn clean verify`
=> Set server on `WebApplicationContext`

src/test/java/winstone/FormSubmissionTest.java
Fixes #284
Chase away flakiness by running the relevant request in a loop until it passes.
Ran this test in a loop. Before this PR, it would fail within 10 iterations. Now I've run over 100 iterations with no failures.
=> `FormSubmissionTest#largeForm` is flaky

src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/cmdline/Option.java
The documentation states that the Winstone default is 10,000 (unlike the Jetty default of 1,000), but this statement is false, as Winstone only sets the value if the user specifies the option, and otherwise uses the Jetty default. Since Stapler forms are complex and often need thousands of parameters, this PR adjusts Winstone to match its own documentation and use a limit of 10,000.
- `mvn clean verify` passes, including the new automated test added in #393.
- Manually reproduced the scenario described in [JENKINS-73285](https://issues.jenkins.io/browse/JENKINS-73285) and verified that the issue was resolved after this PR on Jetty 12 EE 8.
Fixes jetty/jetty.project#11959
=> [JENKINS-73285] Set maximum parameter count to 10,000 to match the documentation

src/main/java/winstone/Launcher.java
See [JENKINS-73616](https://issues.jenkins.io/browse/JENKINS-73616).
Users have complained that there are new warnings emitted on Jenkins startup.
These duplicates are known to the project and ignored in https://github.com/jenkinsci/jenkins/blob/c5c69abd2d346a694c29b3e5f5d3991d94c38556/test/src/test/java/jenkins/ClassPathTest.java because we cannot upgrade `jansi` without also upgrading Groovy as described in https://github.com/jenkinsci/jenkins/pull/5184#pullrequestreview-570261350 (though I doubt anyone has actually tried?).
Since these warnings are a false positive, turn up the log level for this class from the default level to `SEVERE` so that this log statement is not printed.
Reproduced the issue with `java -jar jenkins.war` and could no longer reproduce after this PR.
=> [JENKINS-73616] Log spam from `AnnotationParser#parseClass`

README.md
The files mentioned by this clause were deleted a long time ago, so delete this clause from the license text to avoid confusion.
=> Remove irrelevant license text

pom.xml, src/main/java/winstone/HostConfiguration.java, src/main/java/winstone/Http2ConnectorFactory.java, src/main/java/winstone/ServerConnectorBuilder.java, src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/Http2ConnectorFactoryTest.java, src/test/java/winstone/HttpConnectorFactoryTest.java, src/test/java/winstone/HttpsConnectorFactoryTest.java, src/test/java/winstone/testApplication/servlets/HelloRestOfPathServlet.java, src/testwebapp/WEB-INF/web.xml
Unit tests written. But I can't get the http2 connector test to work, it fails with whatever uri compliance I set. Is it perhaps not possible in the http2 spec?
=> [JENKINS-75278] Upgrade Jetty 12.0.17 which restore UriCompliance.LEGACY previous behaviour

src/test/java/winstone/AbstractWinstoneTest.java, src/test/java/winstone/Http2ConnectorFactoryTest.java, src/test/java/winstone/HttpConnectorFactoryTest.java, src/test/java/winstone/HttpsConnectorFactoryTest.java, src/test/java/winstone/accesslog/SimpleAccessLoggerTest.java
`ClientConnector#forUnixDomain` is deprecated for removal in Jetty 12.1, so replace this with the non-deprecated equivalent `Transport.TCPUnix`. While I was here, I also removed two deprecated test methods and refactored test usage to be more consistent throughout all tests.
`mvn clean verify`, including  `HttpConnectorFactoryTest#testListenUnixDomainPath`
=> Remove usages of deprecated functionality
