pom.xml
=> [INFRA-588] Use new distributionManagement.url

Jenkinsfile
=> add a Jenkinsfile

.gitignore, src/test/winstone/accesslog/SimpleAccessLoggerTest.java
@reviewbybees
Needs #26 merging to prevent regressions also....
=> Fix windows tests

src/java/winstone/HttpsConnectorFactory.java
@reviewbybees JDK 8 moved the `CertAndKeyGen` class to a new location.
This code change uses reflection to make make sure it is compatible with JDK 7 and JDK 8.
Unit tests pass in both JDK 8 and JDK 7 in my local environment:
=> [JENKINS-25333] Self Signed certificates with JDK8

.gitignore, Jenkinsfile, pom.xml, src/java/winstone/HttpsConnectorFactory.java, src/java/winstone/LocalStrings.properties
[JENKINS-25333](https://issues.jenkins-ci.org/browse/JENKINS-25333)
Subsumes #23 and #28.
@reviewbybees
=> [JENKINS-25333] Avoid hard dependency on non-Java-Platform APIs

src/java/winstone/accesslog/SimpleAccessLogger.java
[JENKINS-37625] Don’t get the request.remoteUser if it’s a deferred authentication (`org.eclipse.jetty.server.Authentication.Deferred`) to prevent "IllegalStateException: Response is committed"
```
java.lang.IllegalStateException: Response is committed
at org.eclipse.jetty.server.Request.getSession(Request.java:1400)
at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:260)
at org.eclipse.jetty.security.authentication.DeferredAuthentication.authenticate(DeferredAuthentication.java:68)
at org.eclipse.jetty.server.Request.getUserPrincipal(Request.java:1479)
at org.eclipse.jetty.server.Request.getRemoteUser(Request.java:1087)
at winstone.accesslog.SimpleAccessLogger.log(SimpleAccessLogger.java:89)
at …
```
=> [JENKINS-37625] Don’t get the request.remoteUser if it’s a deferred authentication

README.md
Added requestHeaderSize as available command-line option
=> Update README.md: Added requestHeaderSize to Command-line options

README.md, pom.xml, src/java/winstone/AbstractSecuredConnectorFactory.java, src/java/winstone/Http2ConnectorFactory.java, src/java/winstone/HttpsConnectorFactory.java, src/java/winstone/Launcher.java, src/java/winstone/LocalStrings.properties, src/java/winstone/cmdline/Option.java, src/test/winstone/HttpsConnectorFactoryTest.java
https://issues.jenkins-ci.org/browse/JENKINS-45438
=> [JENKINS-45438] Add HTTP/2 connector

CHANGELOG.md, pom.xml, src/java/winstone/HostConfiguration.java, src/java/winstone/Http2ConnectorFactory.java, src/java/winstone/LocalStrings.properties, src/java/winstone/cmdline/Option.java
@oleg-nenashev  it looks I cannot push anymore directly....
so feel free to merge this.
=> some minor changes

CHANGELOG.md, README.md, src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
add an extra lib directory option to be able to add alpn processor
Signed-off-by: olivier lamy <olamy@apache.org>
=> [JENKINS-52358] fix broken http/2 support

CHANGELOG.md, pom.xml
=> Facelift POM and add changelog

CHANGELOG.md, pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
=> jetty 9.4.15.v20190215 upgrade

pom.xml
Draft update for https://github.com/jenkinsci/pom/commit/284497123d27be7a1a57ea0d07d83839e41a2af5 . Mostly for testing purposes
=> Upgrade Parent POM to 1.53

Jenkinsfile
https://issues.jenkins-ci.org/browse/JENKINS-60606
=> [JENKINS-60606] - Jenkinsfile: Use standard methods from te Pipeline library to speedup  builds

TODO.txt
=> Remove the obsolete TODO.txt

src/main/java/winstone/Launcher.java
See [JENKINS-57888](https://issues.jenkins-ci.org/browse/JENKINS-57888).
* Logging: Specifying -Djava.util.logging.config.file makes the specifying of a ConsoleHandler possible, which was not possible anymore since winstone 5.4
N/A
* Fill-in the `Proposed changelog entries` section only if there are breaking changes or other changes which may require extra steps from users during the upgrade
@jglick 
Before the changes are marked as `ready-for-merge`:
=> [JENKINS-57888] - Restore `java.util.logging.config.file` property support (regression in 5.4)

README.md, src/main/java/winstone/HttpConnectorFactory.java, src/main/java/winstone/HttpsConnectorFactory.java, src/main/java/winstone/ServerConnectorBuilder.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/HttpsConnectorFactoryTest.java
This adds the ability to configure winstone to redirect http requests to https automatically.
=> Add ability to redirect http to https

src/main/java/winstone/HttpConnectorFactory.java, src/main/java/winstone/HttpsConnectorFactory.java, src/main/java/winstone/cmdline/Option.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> [JENKINS-61823] - Fix '--httpKeepAliveTimeout' option which had no effect in 5.9

src/test/java/winstone/HttpsConnectorFactoryTest.java
=> use of dynamic port for http redirect to https test

pom.xml
=> Fix incrementals support

pom.xml
https://github.com/jenkinsci/plugin-pom/blob/3d0c3d0ee03104b2650d0d8c5b71e02aeefcc3d8/pom.xml#L262-L266
=> Test annotations should be in test scope

src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/test/java/winstone/HttpsConnectorFactoryTest.java
see https://github.com/jenkinsci/winstone/pull/181#issuecomment-1032544226
=> Remove automatic self signed cert if tls specified but no keystore

src/test/java/winstone/HttpConnectorFactoryTest.java
It's in the README but I missed it, if it had been in the test I think I would have found the issue without having to google for a bit
=> Add additional note on loopback address to test

src/main/java/winstone/Launcher.java
as requested here https://github.com/jenkinsci/winstone/pull/181#discussion_r802080667
=> remove obvious non needed cast

.github/dependabot.yml
=> for now ignore jetty upgrade >= 10

src/main/java/winstone/HttpConnectorFactory.java, src/main/java/winstone/HttpsConnectorFactory.java, src/main/java/winstone/ServerConnectorBuilder.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties
https://issues.jenkins.io/browse/JENKINS-68386
https://issues.jenkins.io/browse/JENKINS-68379
=> [JENKINS-68386] add option to set responseHeaderSize

.github/dependabot.yml, Jenkinsfile, README.md, pom.xml, src/main/java/winstone/AbstractSecuredConnectorFactory.java, src/main/java/winstone/HostGroup.java, src/main/java/winstone/Http2ConnectorFactory.java, src/main/java/winstone/HttpsConnectorFactory.java, src/main/java/winstone/Launcher.java, src/main/java/winstone/ServerConnectorBuilder.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/HttpsConnectorFactoryTest.java, src/test/resources/jul.properties
=> Upgrade Jetty to 10.0.11

src/main/resources/winstone/LocalStrings.properties
missed in https://github.com/jenkinsci/winstone/pull/203
=> Remove unused resource bundle key

Jenkinsfile
Reverts https://github.com/jenkinsci/winstone/pull/181/commits/6c42ee9a6392fccb424a1b18bc7a05e19c4e0993
=> Add Java 17 on CI

src/main/java/winstone/HostConfiguration.java
https://github.com/jenkinsci/jenkins/pull/6785#discussion_r914305175 says it all.
=> [JENKINS-68933] Enable WebSocket

pom.xml, src/main/java/winstone/Launcher.java, src/test/java/winstone/HttpConnectorFactoryTest.java
=> Write port value atomically

pom.xml
=> Upgrade to Jetty 10.0.20

README.md, src/main/java/winstone/Launcher.java, src/main/java/winstone/cmdline/Option.java, src/main/resources/winstone/LocalStrings.properties, src/test/java/winstone/LauncherTest.java
This was deprecated for removal "on or after January 1, 2023," a date which we are well past.
`mvn clean verify`
=> Remove `--extraLibFolder`

src/test/java/winstone/FormSubmissionTest.java
Add a minimal reproducible test case for [JENKINS-73285](https://issues.jenkins.io/browse/JENKINS-73285). I plan to submit an upstream Jetty issue report for this, using this test as an example. The test passes on Jetty 10 and starts failing on Jetty 12 EE 8.
Ran the test successfully on Jetty 10. On Jetty 12 EE 8 the test fails with the stack trace reported in the issue.
=> Add automated test for JENKINS-73285

pom.xml
=> Upgrade to Jetty 10.0.24 

pom.xml
While trying to get Jenkins running with Jetty 12.1.1 and Java 25, I noticed that the incremental builds of main branch were not correctly deployed. 
https://ci.jenkins.io/job/Core/job/winstone/job/master/514/pipeline-overview/?selected-node=163 still marked as successful but got `Wrong commit hash in /project/scm/tag,`.
This is to fix this.
I ran `mvn -Dset.changelist -DskipTests clean install` and could get the incremental build locally.
=> Fixes `project.scm.tag` for incremental
